[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ebox-fem-phase1"
version = "0.1.0"
description = "Primera fase para automatizar la correlacion FEM estructural de una E-Box"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "pyyaml",
  "pandas",
  "numpy",
  "pyNastran",
  "typer",
  "pytest",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[tool.setuptools]
packages = ["src"]
